#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     irSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     DumpMotorLeft, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     DumpMotorRight, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     SpinnyThing,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     LeftDrive,     tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C3_2,     RightDrive,    tmotorTetrix, openLoop, driveRight)
#pragma config(Servo,  srvo_S1_C4_1,    SideHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    BackHook,             tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.




void initializeRobot()
{
	eraseDisplay();

	return;
}



task main()
{
	initializeRobot();


	waitForStart(); // Wait for the beginning of autonomous phase.
	motor[LeftDrive]=-75;//turn on the left motor
	motor[RightDrive]=75;//turn on the right motor
	wait1Msec(1800);//continue the motors
	motor[LeftDrive]=0;//turn off the left motor
	motor[RightDrive]=0;//turn off the right motor

}
